/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf 
Author: Vetech82 (https://sketchfab.com/Vetech82)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/police-drone-viper-zx07-c118815778f146bbb8e69db5acfc9d8e
Title: Police Drone - Viper ZX07
*/
"use client";

import React, { useEffect } from 'react'
import { useFrame, useGraph, useLoader, useThree } from '@react-three/fiber'
import { useGLTF, useAnimations, useScroll } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { GLTFLoader } from 'three/examples/jsm/Addons.js';
export default function Model(props) {
  const group = React.useRef()
  const scroll = useScroll()
  // const scene = useLoader(GLTFLoader, '/police/scene.gltf')
  const { scene, animations } = useGLTF("/police/scene.gltf", true)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names, mixer, clips, ref } = useAnimations(animations, group)
  useFrame(() => {
    mixer.timeScale = scroll.offset / 20
    actions?.Scene?.play()
    console.log(scroll)
  }, [mixer]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="a6b609774e044f4f8e8471559c828f46fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="MachineGun" position={[57.873, -50.478, -0.366]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Rig" position={[83.08, -30.042, -0.738]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_8" position={[57.873, -50.478, -0.366]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_36" position={[167.449, -38.436, -40.153]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_40" position={[114.078, -44.967, -51.369]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_44" position={[114.482, -44.383, 50.265]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_48" position={[167.449, -38.436, 39.415]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_52" position={[78.157, -15.043, -0.369]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_61" position={[77.779, -30.987, -0.447]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_65" position={[77.779, -32.494, -0.447]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_69" position={[66.958, -29.58, 43.501]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_73" position={[78.157, -15.043, -0.369]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_77" position={[66.958, -29.58, -44.238]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_81" position={[17.485, -15.917, -120.816]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_85" position={[175.501, -27.904, -119.885]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_89" position={[175.493, -28.354, 115.979]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_93" position={[18.575, -13.859, -121.432]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_97" position={[18.575, -23.661, -121.433]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_101" position={[184.776, -26.101, 129.948]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_105" position={[184.776, -34.859, 129.941]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_109" position={[184.826, -34.357, -130.714]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_113" position={[184.826, -27.091, -130.705]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_117" position={[18.56, -21.481, 120.748]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_121" position={[18.56, -14.897, 120.755]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material03} skeleton={nodes.Object_9.skeleton} />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Material02} skeleton={nodes.Object_10.skeleton} />
                    <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Material01} skeleton={nodes.Object_11.skeleton} />
                    <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Material02} skeleton={nodes.Object_37.skeleton} />
                    <skinnedMesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.Material03} skeleton={nodes.Object_38.skeleton} />
                    <skinnedMesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.Material01} skeleton={nodes.Object_39.skeleton} />
                    <skinnedMesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.Material03} skeleton={nodes.Object_41.skeleton} />
                    <skinnedMesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.Material02} skeleton={nodes.Object_42.skeleton} />
                    <skinnedMesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Material01} skeleton={nodes.Object_43.skeleton} />
                    <skinnedMesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.Material03} skeleton={nodes.Object_45.skeleton} />
                    <skinnedMesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.Material02} skeleton={nodes.Object_46.skeleton} />
                    <skinnedMesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.Material01} skeleton={nodes.Object_47.skeleton} />
                    <skinnedMesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.Material02} skeleton={nodes.Object_49.skeleton} />
                    <skinnedMesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.Material03} skeleton={nodes.Object_50.skeleton} />
                    <skinnedMesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.Material01} skeleton={nodes.Object_51.skeleton} />
                    <skinnedMesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.Material01} skeleton={nodes.Object_53.skeleton} />
                    <skinnedMesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.Material01} skeleton={nodes.Object_54.skeleton} />
                    <skinnedMesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.Material02} skeleton={nodes.Object_55.skeleton} />
                    <skinnedMesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Material03} skeleton={nodes.Object_56.skeleton} />
                    <skinnedMesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.Material03} skeleton={nodes.Object_57.skeleton} />
                    <skinnedMesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.Cameras} skeleton={nodes.Object_58.skeleton} />
                    <skinnedMesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.Glasss_right} skeleton={nodes.Object_59.skeleton} />
                    <skinnedMesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.Glass_left} skeleton={nodes.Object_60.skeleton} />
                    <skinnedMesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.emmison_red} skeleton={nodes.Object_62.skeleton} />
                    <skinnedMesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.Material01} skeleton={nodes.Object_63.skeleton} />
                    <skinnedMesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.emmision_blue} skeleton={nodes.Object_64.skeleton} />
                    <skinnedMesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.emmison_red} skeleton={nodes.Object_66.skeleton} />
                    <skinnedMesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.Material01} skeleton={nodes.Object_67.skeleton} />
                    <skinnedMesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.emmision_blue} skeleton={nodes.Object_68.skeleton} />
                    <skinnedMesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.Material02} skeleton={nodes.Object_70.skeleton} />
                    <skinnedMesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.Material03} skeleton={nodes.Object_71.skeleton} />
                    <skinnedMesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.Material01} skeleton={nodes.Object_72.skeleton} />
                    <skinnedMesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.Material02} skeleton={nodes.Object_74.skeleton} />
                    <skinnedMesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.Material03} skeleton={nodes.Object_75.skeleton} />
                    <skinnedMesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.Material01} skeleton={nodes.Object_76.skeleton} />
                    <skinnedMesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.Material03} skeleton={nodes.Object_78.skeleton} />
                    <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.Material02} skeleton={nodes.Object_79.skeleton} />
                    <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.Material01} skeleton={nodes.Object_80.skeleton} />
                    <skinnedMesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.Material02} skeleton={nodes.Object_82.skeleton} />
                    <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Material01} skeleton={nodes.Object_83.skeleton} />
                    <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.Material03} skeleton={nodes.Object_84.skeleton} />
                    <skinnedMesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.Material02} skeleton={nodes.Object_86.skeleton} />
                    <skinnedMesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.Material01} skeleton={nodes.Object_87.skeleton} />
                    <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.Material03} skeleton={nodes.Object_88.skeleton} />
                    <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.Material02} skeleton={nodes.Object_90.skeleton} />
                    <skinnedMesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.Material01} skeleton={nodes.Object_91.skeleton} />
                    <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.Material03} skeleton={nodes.Object_92.skeleton} />
                    <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.Material01} skeleton={nodes.Object_94.skeleton} />
                    <skinnedMesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.Material03} skeleton={nodes.Object_95.skeleton} />
                    <skinnedMesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.Material02} skeleton={nodes.Object_96.skeleton} />
                    <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.Material01} skeleton={nodes.Object_98.skeleton} />
                    <skinnedMesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.Material02} skeleton={nodes.Object_99.skeleton} />
                    <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.Material03} skeleton={nodes.Object_100.skeleton} />
                    <skinnedMesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.Material01} skeleton={nodes.Object_102.skeleton} />
                    <skinnedMesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.Material02} skeleton={nodes.Object_103.skeleton} />
                    <skinnedMesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.Material03} skeleton={nodes.Object_104.skeleton} />
                    <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.Material03} skeleton={nodes.Object_106.skeleton} />
                    <skinnedMesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.Material02} skeleton={nodes.Object_107.skeleton} />
                    <skinnedMesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.Material01} skeleton={nodes.Object_108.skeleton} />
                    <skinnedMesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.Material02} skeleton={nodes.Object_110.skeleton} />
                    <skinnedMesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials.Material01} skeleton={nodes.Object_111.skeleton} />
                    <skinnedMesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.Material03} skeleton={nodes.Object_112.skeleton} />
                    <skinnedMesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.Material02} skeleton={nodes.Object_114.skeleton} />
                    <skinnedMesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials.Material03} skeleton={nodes.Object_115.skeleton} />
                    <skinnedMesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.Material01} skeleton={nodes.Object_116.skeleton} />
                    <skinnedMesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.Material02} skeleton={nodes.Object_118.skeleton} />
                    <skinnedMesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.Material03} skeleton={nodes.Object_119.skeleton} />
                    <skinnedMesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.Material01} skeleton={nodes.Object_120.skeleton} />
                    <skinnedMesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.Material02} skeleton={nodes.Object_122.skeleton} />
                    <skinnedMesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.Material03} skeleton={nodes.Object_123.skeleton} />
                    <skinnedMesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.Material01} skeleton={nodes.Object_124.skeleton} />
                  </group>
                </group>
                <group name="Holder_back_L" position={[167.449, -38.436, -40.153]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Holder_front_R" position={[114.078, -44.967, -51.369]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Holder_front_L" position={[114.482, -44.383, 50.265]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Holder_back_R" position={[167.449, -38.436, 39.415]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Body" position={[78.157, -15.043, -0.369]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Body001" position={[77.779, -30.987, -0.447]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Body002" position={[77.779, -32.494, -0.447]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="front_arm_01_L" position={[66.958, -29.58, 43.501]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="front_arm_02_L" position={[78.157, -15.043, -0.369]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="front_arm_01_R" position={[66.958, -29.58, -44.238]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="front_arm_02_R" position={[17.485, -15.917, -120.816]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="back_arm_01_R" position={[175.501, -27.904, -119.885]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="back_arm_01_L" position={[175.493, -28.354, 115.979]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="propeler_Front_Top_R" position={[18.575, -13.859, -121.432]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="propeler_Front_Bottom_R" position={[18.575, -23.661, -121.433]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="propeler_Back_Bottom_L" position={[184.776, -26.101, 129.948]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="propeler_Back_Bottom_L001" position={[184.776, -34.859, 129.941]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="propeler_Back_Bottom_R" position={[184.826, -34.357, -130.714]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="propeler_Back_Top_R" position={[184.826, -27.091, -130.705]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="propeler_Front_Bottom_L" position={[18.56, -21.481, 120.748]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="propeler_Front_Top_L" position={[18.56, -14.897, 120.755]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
